# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bg3modsFeed < Formula
  desc "A feed generator of mods for Baldur's Gate 3"
  homepage "https://github.com/tinyzimmer/bg3mods-feed"
  version "0.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.3/bg3mods-feed_Darwin_x86_64.tar.gz"
      sha256 "a04827a6d85422c04474e0feb62e700da933731bd3a580067d59eb1c899a784c"

      def install
        bin.install "bg3mods-feed"
        pkgetc.install "contrib/etc/config.yaml" => "bg3mods-feed.conf.yaml" if !File.exist?(pkgetc/"bg3mods-feed.conf.yaml")
      end
    end
    on_arm do
      url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.3/bg3mods-feed_Darwin_arm64.tar.gz"
      sha256 "02b8a37098b4f1b8693c21f3fa4498e3dc507c2077363ba2a15821c1fd883128"

      def install
        bin.install "bg3mods-feed"
        pkgetc.install "contrib/etc/config.yaml" => "bg3mods-feed.conf.yaml" if !File.exist?(pkgetc/"bg3mods-feed.conf.yaml")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.3/bg3mods-feed_Linux_x86_64.tar.gz"
        sha256 "6d69289df08eab97f52b1c7ac353231c6629f6caf964c87c351ac1f6430dcd30"

        def install
          bin.install "bg3mods-feed"
          pkgetc.install "contrib/etc/config.yaml" => "bg3mods-feed.conf.yaml" if !File.exist?(pkgetc/"bg3mods-feed.conf.yaml")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.3/bg3mods-feed_Linux_arm64.tar.gz"
        sha256 "1f82d15d9a90d5e4fde9ab65cb23fda431256c1d8e17b05a63b3b6e935503bf3"

        def install
          bin.install "bg3mods-feed"
          pkgetc.install "contrib/etc/config.yaml" => "bg3mods-feed.conf.yaml" if !File.exist?(pkgetc/"bg3mods-feed.conf.yaml")
        end
      end
    end
  end

  def caveats
    <<~EOS
      You can start the service with `brew services start bg3mods-feed`.
      The service will be available at http://localhost:8080/feed unless otherwise configured in #{pkgetc}/bg3mods-feed.conf.yaml.
    EOS
  end

  service do
    run [bin/"bg3mods-feed", "--config", pkgetc/"bg3mods-feed.conf.yaml"]
    keep_alive true
  end

  test do
    system "#{bin}/bg3mods-feed --version"
  end
end
