# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bg3modsFeed < Formula
  desc "A feed generator of mods for Baldur's Gate 3"
  homepage "https://github.com/tinyzimmer/bg3mods-feed"
  version "0.0.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.4/bg3mods-feed_Darwin_x86_64.tar.gz"
      sha256 "803797313cbc6ecad3f60acfda1fe8178f2641f22f098285df633a7c39633646"

      def install
        bin.install "bg3mods-feed"
        etc.install "contrib/etc/config.yaml" => "bg3mods-feed.conf.yaml" if !File.exist?(etc/"bg3mods-feed.conf.yaml")
      end
    end
    on_arm do
      url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.4/bg3mods-feed_Darwin_arm64.tar.gz"
      sha256 "17807f267923c8c0d51c54637790ab839ee1d2282a377feba5019aa3c3f62fe1"

      def install
        bin.install "bg3mods-feed"
        etc.install "contrib/etc/config.yaml" => "bg3mods-feed.conf.yaml" if !File.exist?(etc/"bg3mods-feed.conf.yaml")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.4/bg3mods-feed_Linux_x86_64.tar.gz"
        sha256 "b73bd5e4d1ac1d1b7f5519c3df2200ea52b7b3b9716a48204ab638fd5f1d9575"

        def install
          bin.install "bg3mods-feed"
          etc.install "contrib/etc/config.yaml" => "bg3mods-feed.conf.yaml" if !File.exist?(etc/"bg3mods-feed.conf.yaml")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.4/bg3mods-feed_Linux_arm64.tar.gz"
        sha256 "750a6cc218c33056554f31aded39745be6908546fde597bb2fef461189dc1817"

        def install
          bin.install "bg3mods-feed"
          etc.install "contrib/etc/config.yaml" => "bg3mods-feed.conf.yaml" if !File.exist?(etc/"bg3mods-feed.conf.yaml")
        end
      end
    end
  end

  def caveats
    <<~EOS
      You can start the service with `brew services start bg3mods-feed`.
      The service will be available at http://localhost:8080/feed unless otherwise configured in #{etc}/bg3mods-feed.conf.yaml.
    EOS
  end

  service do
    run [bin/"bg3mods-feed", "--config", etc/"bg3mods-feed.conf.yaml"]
    keep_alive true
  end

  test do
    system "#{bin}/bg3mods-feed --version"
  end
end
