# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bg3modsFeed < Formula
  desc "A feed generator of mods for Baldur's Gate 3"
  homepage "https://github.com/tinyzimmer/bg3mods-feed"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.1/bg3mods-feed_Darwin_x86_64.tar.gz"
      sha256 "82472894ff5e5e79f67d9c311693c6d8fd5eabfaf4c22d6163f15343855ad8aa"

      def install
        bin.install "bg3mods-feed"
      end
    end
    on_arm do
      url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.1/bg3mods-feed_Darwin_arm64.tar.gz"
      sha256 "fb0d32d7bfffb60baeb6d081f41512f1572cf753fef5f7c3edee5e63ce2884f9"

      def install
        bin.install "bg3mods-feed"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.1/bg3mods-feed_Linux_x86_64.tar.gz"
        sha256 "e4f7e810ab607972fc0a0ac7fea0389957eff0fbe535ec82c14e4cad6c59ff55"

        def install
          bin.install "bg3mods-feed"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tinyzimmer/bg3mods-feed/releases/download/v0.0.1/bg3mods-feed_Linux_arm64.tar.gz"
        sha256 "16176bde5f8e1989336f5154a301ef12cb2e20852ab745efc45d877d2e2edaee"

        def install
          bin.install "bg3mods-feed"
        end
      end
    end
  end

  def caveats
    <<~EOS
      You can start the service with `brew services start bg3mods-feed`.
      The service will be available at http://localhost:#{ENV['BG3MODS_LISTEN_PORT'] || '8080'}/feed.
    EOS
  end

  service do
    run "#{bin}/bg3mods-feed"
    keep_alive true
    environment_variables
      BG3MODS_LISTEN: ":#{ENV['BG3MODS_LISTEN_PORT'] || '8080'}"
      BG3MODS_TAGS: "#{ENV['BG3MODS_TAGS'] || ''}"
      BG3MODS_PLATFORM: "#{ENV['BG3MODS_PLATFORM'] || ''}"
      BG3MODS_MAX_FEED_ITEMS: "#{ENV['BG3MODS_MAX_FEED_ITEMS'] || '100'}"
      BG3MODS_SORT: "#{ENV['BG3MODS_SORT'] || 'recent'}"
      BG3MODS_FETCH_INTERVAL: "#{ENV['BG3MODS_FETCH_INTERVAL'] || '5m'}"
      BG3MODS_FORMAT: "#{ENV['BG3MODS_FORMAT'] || 'atom'}"
    sockets "tcp://127.0.0.1:#{ENV['BG3MODS_LISTEN_PORT'] || '8080'}"
  end

  test do
    system "#{bin}/bg3mods-feed --version"
  end
end
